package views.geral;

/**
 *
 * @author rhau
 */
public class MainWindowView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public MainWindowView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        lblTitulo = new javax.swing.JLabel();
        pnlGerenciar = new javax.swing.JPanel();
        btnLivros = new javax.swing.JButton();
        btnAlunos = new javax.swing.JButton();
        btnProfessores = new javax.swing.JButton();
        pnlAlunos = new javax.swing.JPanel();
        btnReservasAlunos = new javax.swing.JButton();
        btnEmprestimosAlunos = new javax.swing.JButton();
        btnMultasAluno = new javax.swing.JButton();
        pnlProf = new javax.swing.JPanel();
        btnReservasProfs = new javax.swing.JButton();
        btnEmprestimosProfs = new javax.swing.JButton();
        btnMultasProfs = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuMais = new javax.swing.JMenu();
        maisSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema da biblioteca\n");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        lblTitulo.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(75, 192, 183));
        lblTitulo.setText("Sistema da Biblioteca");

        pnlGerenciar.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciar"));
        pnlGerenciar.setLayout(new java.awt.GridLayout(1, 0));

        btnLivros.setText("Livros");
        btnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivrosActionPerformed(evt);
            }
        });
        pnlGerenciar.add(btnLivros);

        btnAlunos.setText("Alunos");
        btnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunosActionPerformed(evt);
            }
        });
        pnlGerenciar.add(btnAlunos);

        btnProfessores.setText("Professores");
        btnProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessoresActionPerformed(evt);
            }
        });
        pnlGerenciar.add(btnProfessores);

        pnlAlunos.setBorder(javax.swing.BorderFactory.createTitledBorder("Alunos"));
        pnlAlunos.setLayout(new java.awt.BorderLayout());

        btnReservasAlunos.setText("Reservas");
        btnReservasAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasAlunosActionPerformed(evt);
            }
        });
        pnlAlunos.add(btnReservasAlunos, java.awt.BorderLayout.CENTER);

        btnEmprestimosAlunos.setText("Empréstimos");
        btnEmprestimosAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimosAlunosActionPerformed(evt);
            }
        });
        pnlAlunos.add(btnEmprestimosAlunos, java.awt.BorderLayout.PAGE_START);

        btnMultasAluno.setText("Multas");
        btnMultasAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultasAlunoActionPerformed(evt);
            }
        });
        pnlAlunos.add(btnMultasAluno, java.awt.BorderLayout.PAGE_END);

        pnlProf.setBorder(javax.swing.BorderFactory.createTitledBorder("Professores"));
        pnlProf.setLayout(new java.awt.BorderLayout());

        btnReservasProfs.setText("Reservas");
        btnReservasProfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasProfsActionPerformed(evt);
            }
        });
        pnlProf.add(btnReservasProfs, java.awt.BorderLayout.CENTER);

        btnEmprestimosProfs.setText("Empréstimos");
        btnEmprestimosProfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimosProfsActionPerformed(evt);
            }
        });
        pnlProf.add(btnEmprestimosProfs, java.awt.BorderLayout.PAGE_START);

        btnMultasProfs.setText("Multas");
        btnMultasProfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultasProfsActionPerformed(evt);
            }
        });
        pnlProf.add(btnMultasProfs, java.awt.BorderLayout.PAGE_END);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        menuInicio.setText("Inicio");
        barraMenu.add(menuInicio);

        menuMais.setText("Mais");
        menuMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaisActionPerformed(evt);
            }
        });

        maisSobre.setText("Sobre");
        maisSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisSobreActionPerformed(evt);
            }
        });
        menuMais.add(maisSobre);

        barraMenu.add(menuMais);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pnlProf, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    protected void menuMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaisActionPerformed
    }//GEN-LAST:event_menuMaisActionPerformed

    protected void maisSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maisSobreActionPerformed

    protected void btnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLivrosActionPerformed

    protected void btnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlunosActionPerformed

    protected void btnProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfessoresActionPerformed

    protected void btnEmprestimosProfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimosProfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmprestimosProfsActionPerformed

    protected void btnEmprestimosAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimosAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmprestimosAlunosActionPerformed

    protected void btnReservasAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservasAlunosActionPerformed

    protected void btnReservasProfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasProfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservasProfsActionPerformed

    protected void btnMultasAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultasAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultasAlunoActionPerformed

    protected void btnMultasProfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultasProfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultasProfsActionPerformed

    protected void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindowView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnAlunos;
    private javax.swing.JButton btnEmprestimosAlunos;
    private javax.swing.JButton btnEmprestimosProfs;
    private javax.swing.JButton btnLivros;
    private javax.swing.JButton btnMultasAluno;
    private javax.swing.JButton btnMultasProfs;
    private javax.swing.JButton btnProfessores;
    private javax.swing.JButton btnReservasAlunos;
    private javax.swing.JButton btnReservasProfs;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem maisSobre;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuMais;
    private javax.swing.JPanel pnlAlunos;
    private javax.swing.JPanel pnlGerenciar;
    private javax.swing.JPanel pnlProf;
    // End of variables declaration//GEN-END:variables
}
