/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.professor;

import views.geral.LivroView;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Professor;
import model.dao.ProfessorDAO;
import util.VerificaString;

/**
 *
 * @author rhau
 */
public class ProfessorView extends javax.swing.JDialog {

    ProfessorDAO pdao = new ProfessorDAO();

    public void atualizaTabela() throws SQLException {
        listProfessores.clear();
        listProfessores.addAll(pdao.buscarTodos());
        int linha = listProfessores.size() - 1;
        if (linha >= 0) {
            tblProfessores.setRowSelectionInterval(linha, linha);
            tblProfessores.scrollRectToVisible(
                    tblProfessores.getCellRect(linha, linha, true));
            barra_navegacao(true);
        } else {
            limpa_campos();
            barra_navegacao(false);
        }
        txtBusca.setText("");
    }

    public void trataEdicao(boolean editando) {
        // botoes ativados se estivar editando 
        btnCancelar.setEnabled(editando);
        btnSalvar.setEnabled(editando);
        // botoes desativados se estivar editando 
        btnEditar.setEnabled(!editando);
        btnExcluir.setEnabled(!editando);
        btnNovo.setEnabled(!editando);
        btnFechar.setEnabled(!editando);
        btnPrimeiro.setEnabled(!editando);
        btnProximo.setEnabled(!editando);
        btnAnterior.setEnabled(!editando);
        btnUltimo.setEnabled(!editando);
        btnBusca.setEnabled(!editando);
        // campos ativados se estivar editando 
        txtMatricula.setEditable(editando);
        txtNome.setEditable(editando);
        txtMulta.setEditable(editando);
        txtLivros.setEditable(editando);
        txtLogin.setEditable(editando);
        // desativado
        txtBusca.setEditable(!editando);
        // tabela
        tblProfessores.setEnabled(!editando);
    }

    public boolean validaCampos() {
        if (txtVazio(txtLogin, "o login")) {
            return false;
        }
        
        if (txtVazio(txtMatricula, "a matricula")) {
            return false;
        }

        if (!VerificaString.ehNumero(txtMatricula.getText())) {
            JOptionPane.showMessageDialog(null, "A matrícula deve conter apenas números");
            txtMatricula.requestFocus();
            return false;
        }

        if (txtVazio(txtNome, "o nome")) {
            return false;
        }

        if (txtMulta.getText().isEmpty()) {
            txtMulta.setText("0");
        }

        if (txtLivros.getText().isEmpty()) {
            txtLivros.setText("0");
        }

        if (!VerificaString.ehNumero(txtLivros.getText())) {
            JOptionPane.showMessageDialog(null, "O número de livros deve conter apenas números");
            txtLivros.requestFocus();
            return false;
        }

        return true;
    }

    public boolean txtVazio(JTextField txt, String msg) {
        if (txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe " + msg + " do professor");
            txt.requestFocus();
            return true;
        }

        return false;
    }

    public void limpa_campos() {
        txtCodigo.setText("");
        txtMatricula.setText("");
        txtNome.setText("");
        txtLivros.setText("");
        txtMulta.setText("");
    }
    
    public void barra_navegacao(Boolean b) {
        btnPrimeiro.setEnabled(b);
        btnAnterior.setEnabled(b);
        btnProximo.setEnabled(b);
        btnUltimo.setEnabled(b);
    }   

    // Construtor
    public ProfessorView(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        trataEdicao(false);
        atualizaTabela();
        if (listProfessores.size() - 1 >= 0) {
            tblProfessores.setRowSelectionInterval(0, 0);
            tblProfessores.scrollRectToVisible(tblProfessores.getCellRect(0, 0, true));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listProfessores = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Professor>())
        ;
        painelAuxiliar = new javax.swing.JPanel();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblProfessoresTitulo = new javax.swing.JLabel();
        btnBusca = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        abas = new javax.swing.JTabbedPane();
        abaProfessores = new javax.swing.JPanel();
        spainelTbl = new javax.swing.JScrollPane();
        tblProfessores = new javax.swing.JTable();
        abaDados = new javax.swing.JPanel();
        painelOpcoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtMulta = new javax.swing.JTextField();
        lblMulta = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblMatricula = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblAutomatico = new javax.swing.JLabel();
        lblLivros = new javax.swing.JLabel();
        txtLivros = new javax.swing.JTextField();
        lblRs = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        lblInfoMulta = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de professores");
        setResizable(false);

        painelAuxiliar.setBorder(javax.swing.BorderFactory.createTitledBorder("Ferramentas auxiliares"));
        painelAuxiliar.setLayout(new java.awt.GridLayout(1, 0));

        btnPrimeiro.setText("Primeiro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });
        painelAuxiliar.add(btnPrimeiro);

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        painelAuxiliar.add(btnAnterior);

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        painelAuxiliar.add(btnProximo);

        btnUltimo.setText("Último");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        painelAuxiliar.add(btnUltimo);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        painelAuxiliar.add(btnFechar);

        lblProfessoresTitulo.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        lblProfessoresTitulo.setForeground(new java.awt.Color(75, 192, 183));
        lblProfessoresTitulo.setText("Gerenciamento de professores");

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        abaProfessores.setLayout(new java.awt.BorderLayout());

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listProfessores, tblProfessores);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${matricula}"));
        columnBinding.setColumnName("Matrícula");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nrLivros}"));
        columnBinding.setColumnName("Livros ");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorMulta}"));
        columnBinding.setColumnName("Multa (R$)");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        spainelTbl.setViewportView(tblProfessores);
        if (tblProfessores.getColumnModel().getColumnCount() > 0) {
            tblProfessores.getColumnModel().getColumn(0).setMinWidth(100);
            tblProfessores.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblProfessores.getColumnModel().getColumn(0).setMaxWidth(100);
            tblProfessores.getColumnModel().getColumn(2).setMinWidth(80);
            tblProfessores.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblProfessores.getColumnModel().getColumn(2).setMaxWidth(80);
            tblProfessores.getColumnModel().getColumn(3).setMinWidth(80);
            tblProfessores.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblProfessores.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        abaProfessores.add(spainelTbl, java.awt.BorderLayout.CENTER);

        abas.addTab("Listagem dos professores", abaProfessores);

        painelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));
        painelOpcoes.setLayout(new java.awt.GridLayout(1, 0));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnEditar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnCancelar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnSalvar);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnExcluir);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblProfessores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.valorMulta}"), txtMulta, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblMulta.setText("Valor multa");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblProfessores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.matricula}"), txtMatricula, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblMatricula.setText("Matrícula");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblProfessores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), txtNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblNome.setText("Nome");

        txtCodigo.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblProfessores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codigo}"), txtCodigo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblCodigo.setText("Código");

        lblAutomatico.setText("(Automático)");

        lblLivros.setText("Livros Reservados");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblProfessores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nrLivros}"), txtLivros, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        lblRs.setText("R$");

        lblMax.setText("(Máximo 5)");

        lblInfoMulta.setText("(Calculado automaticamente)");

        lblLogin.setText("Login");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblProfessores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.login}"), txtLogin, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout abaDadosLayout = new javax.swing.GroupLayout(abaDados);
        abaDados.setLayout(abaDadosLayout);
        abaDadosLayout.setHorizontalGroup(
            abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(abaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaDadosLayout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(32, 32, 32)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblAutomatico))
                    .addGroup(abaDadosLayout.createSequentialGroup()
                        .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(abaDadosLayout.createSequentialGroup()
                                .addComponent(lblLivros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaDadosLayout.createSequentialGroup()
                                .addComponent(lblMulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRs)
                                .addGap(4, 4, 4)
                                .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfoMulta)
                            .addComponent(lblMax)))
                    .addGroup(abaDadosLayout.createSequentialGroup()
                        .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatricula)
                            .addComponent(lblNome)
                            .addComponent(lblLogin))
                        .addGap(18, 18, 18)
                        .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaDadosLayout.setVerticalGroup(
            abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaDadosLayout.createSequentialGroup()
                .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblAutomatico)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatricula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLivros)
                    .addComponent(txtLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMax))
                .addGap(18, 18, 18)
                .addGroup(abaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMulta)
                    .addComponent(lblRs)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoMulta))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        abas.addTab("Dados", abaDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(abas, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelAuxiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblProfessoresTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblProfessoresTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abas, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        tblProfessores.setRowSelectionInterval(0, 0);
        tblProfessores.scrollRectToVisible(tblProfessores.getCellRect(0, 0, true));
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        int linha = tblProfessores.getSelectedRow();
        if ((linha - 1) >= 0) {
            linha--;
        }
        tblProfessores.setRowSelectionInterval(linha, linha);
        tblProfessores.scrollRectToVisible(tblProfessores.getCellRect(linha, 0, true));
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        int linha = tblProfessores.getSelectedRow();
        if ((linha + 1) < tblProfessores.getRowCount()) {
            linha++;
        }
        tblProfessores.setRowSelectionInterval(linha, linha);
        tblProfessores.scrollRectToVisible(tblProfessores.getCellRect(linha, 0, true));
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        int linha = tblProfessores.getRowCount() - 1;
        tblProfessores.setRowSelectionInterval(linha, linha);
        tblProfessores.scrollRectToVisible(tblProfessores.getCellRect(linha, 0, true));
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        String busca = txtBusca.getText();

        if (busca.length() > 0) {
            boolean ehNumero = VerificaString.ehNumero(busca);

            listProfessores.clear();
            if (ehNumero) {
                listProfessores.addAll(pdao.buscarQualquer(pdao.getSqlBuscaMatricula(), 
                        Integer.parseInt(busca))); // matricula 
            } else {
                Professor p = new Professor();
                p.setNome(busca);
                listProfessores.addAll(pdao.buscar(p)); // parte do nome
                listProfessores.addAll(pdao.buscarQualquer(pdao.getSqlBuscaLogin(), busca)); // login
            }
            int linhas = listProfessores.size() - 1;
            if (linhas >= 0) {
                tblProfessores.setRowSelectionInterval(0, 0);
                tblProfessores.scrollRectToVisible(tblProfessores.getCellRect(0, 0, true));
            } else {
                JOptionPane.showConfirmDialog(null, "Nenhuma correspondência encontrada.",
                "Busca sem resultado", JOptionPane.DEFAULT_OPTION);
                try {
                    atualizaTabela();
                } catch (SQLException ex) {
                    Logger.getLogger(LivroView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }     
        } else {
            try {
                atualizaTabela();
            } catch (SQLException ex) {
                Logger.getLogger(LivroView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        listProfessores.add((Professor) new Professor());
        int linhas = listProfessores.size() - 1;
        tblProfessores.setRowSelectionInterval(linhas, linhas);
        trataEdicao(true);
        txtMatricula.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblProfessores.getSelectedRow() >= 0) {
            trataEdicao(true);
            txtMatricula.requestFocus();
        } else {
            JOptionPane.showConfirmDialog(null, 
                    "Algum professor deve ser selecionado para edição.",
                    "Lista de professores vazia", 
                    JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        trataEdicao(false);
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            Logger.getLogger(LivroView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (validaCampos()) {
            int linhaSelecionada = tblProfessores.getSelectedRow();
            Professor p = listProfessores.get(linhaSelecionada);
            if (p.getCodigo() != null) {
                pdao.alterar(p);
            } else {
                pdao.inserir(p);
            }
            trataEdicao(false);
            try {
                atualizaTabela();
            } catch (SQLException ex) {
                Logger.getLogger(LivroView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada = tblProfessores.getSelectedRow();
        if (linhaSelecionada >= 0) {
            if (JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir o professor?",
                    "Confirmar exclusão", JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE,
                    null, new String[]{"Sim", "Não"}, "Sim") == 0) {
                Professor p = listProfessores.get(linhaSelecionada);
                if (p.getValorMulta() > 0) {
                    JOptionPane.showConfirmDialog(null, "Professor possui multa pendente.\n"
                            + "Ação necessária: Quitar a multa.",
                            "Exclusão impossível", JOptionPane.DEFAULT_OPTION);
                    return;
                }
                if (p.getNrLivros() > 0) {
                    JOptionPane.showConfirmDialog(null, "Professor possui livros emprestados.\n"
                            + "Ação necessária: Devolver livros.",
                            "Exclusão impossível", JOptionPane.DEFAULT_OPTION);
                    return;
                }
                pdao.excluir(p);
                try {
                    atualizaTabela();
                    if (listProfessores.size() - 1 >= 0) {
                        tblProfessores.setRowSelectionInterval(0, 0);
                        tblProfessores.scrollRectToVisible(tblProfessores.getCellRect(0, 0, true));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(LivroView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showConfirmDialog(null, "Não há professores para exclusão.",
                    "Lista de professores vazia", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProfessorView dialog = null;
                try {
                    dialog = new ProfessorView(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(ProfessorView.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaDados;
    private javax.swing.JPanel abaProfessores;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel lblAutomatico;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblInfoMulta;
    private javax.swing.JLabel lblLivros;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMulta;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProfessoresTitulo;
    private javax.swing.JLabel lblRs;
    private java.util.List<Professor> listProfessores;
    private javax.swing.JPanel painelAuxiliar;
    private javax.swing.JPanel painelOpcoes;
    private javax.swing.JScrollPane spainelTbl;
    private javax.swing.JTable tblProfessores;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtLivros;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JTextField txtNome;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
